# Generated by Django 5.0.4 on 2024-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
